on: push
jobs:
  setup-graalvm-ce:
    runs-on: ubuntu-latest
    steps:
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: "19.3.0"
          java-version: "java11"
      - name: whereami
        run: pwd
      - name: whatis
        run: ls
      - name: setup-native-image
        run: |
          gu install native-image
      - name: nativebuild    
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: whereami2
        run: pwd
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew nativeImage